### PR TITLE
Update Android References

### PR DESCRIPTION
**Pull request by kspearrin**
- Update Android.Support nuget packages to `25.4.0.2`.
- Compile against Android 8.0 (SDK 26).

Resolves https://github.com/NAXAM/bottomtabbedpage-xamarin-forms/issues/4

### CODE REVIEW

**Comment by kspearrin** [comment]
@tuyen-vuduc Any chance this could get merged and updated soon so that I can stop using a locally referenced dll? 😄

**Comment by tuyen-vuduc** [comment]
@kspearrin Thank you for your effort. I don't have time to check your pull-request in details.

In the meantime, plz don't reference your DLL directly, plz publish a new nuget package with version `1.2.2.1-pre` then use it locally. 

If you don't know how to do it, read a bit more [here](https://blogs.naxam.net/configure-nuget-package-sources-for-your-project-cd8b96397360)

**Comment by kspearrin** [comment]
@tuyen-vuduc I cannot publish to your nuget feed, so I will just continue referencing it locally for now.

**Comment by tuyen-vuduc** [comment]
If you are using a Nuget package locally, it's good. Don't reference DLL locally, it's bad. If you use a package locally, then when the package is updated on Nuget.org, you just need to remove your local package, all'll be good without any modification.

Cheers.

**Review by dothanhbinh41 — APPROVED** [review]

**Comment by kspearrin** [comment]
@dothanhbinh41 Thanks for the merge. Could you please let me know when this will be available on NuGet?

**Pull request merged**
